### ISSUE TITLE
Скорость срабатывания CSS-селекторов. Насколько критично?

### ISSUE THREAD

**Issue by xenongattz** [vitkarpov/ask-me#2]
Собственно, вопрос отражен в топике. Если подробнее, то:
1. Насколько с сегодняшними мощностями браузеров критично использование составных селекторов вроде `.nav .item` против `.nav-item`?
2. Каков порог такого составления (то бишь вкладывания) без удара по производительности? Ведь в проектах не столь глобальных как Яндекс, методология БЭМ не всегда удобна и оправданна.
3. Работает ли селектор по `id` быстрее чем селектор по классу и если да, то почему?
4. Я часто делаю так: `* { box-sizing: border-box }` для удобства. Может лучше стоит перечислять список тегов? Хотя тогда в каскаде появится вязанка тегов а-ля Reset.css. Или тогда уже лучше определять каждый раз когда это реально нужно?
5. Действительно ли такой селектор: `#content * { ... }` браузер поочередно будет пытаться замэтчить ко всем элементам DOM'а пока не найдет те, которые действительно находятся внутри #content?
6. Возможно есть еще какие-то "краеугольные" подводные камни в в этой теме..? Также, буду рад полезным ссылкам по теме, раскрывающим принципы работы селекторного движка в браузерах.

**Comment by vitkarpov** [comment]
Очень хороший вопрос :) Попробуем разобраться по порядку.

Как известно селекторы бывают простые (.foo) и составные (.foo .bar, h1.foo, a[href]). Интуитивно понятно, что простой селектор будет обработано быстрее составного, верно?

Алгоритм, который отвечает в браузере за поиск элементов в DOM в соответствии со списком ЦСС-правил, **начинает свою работу с ключевого селектора** — того, что находится правее всех. Если это простой селектор, то это он и есть, а если составной — то последний, если читать слева направо, как обычно.

Пример работы алгоритма для селектора `.foo .bar`:
- найдем в дереве все `.bar`
- далее отфильтруем среди них те, которые находятся внутри `.foo`

Другой пример, который намекает где реально можно сэкономить, это селектор `button#foo`:
- найдем в дереве узлы с айдишником `foo`
- далее отфильтруем среди них те, которые являются `button`

Элемент с `id` может быть только один. Соответственно, второй шаг — **пустая трата времени**.

Аналогичную логику можно применить к следующим селекторам:

```
.button.red
```

Это кнопка, которая должна быть красной? Не стоит жалеть новых имен для классов — `.red-button`.

```
.aside .button
```

Это кнопка, которая должна быть внутри сайдбара? Аналогично, можно быть чуть более специфичным и назвать ее `.aside-button`.

В соответствии с этой логикой, становится ясно, что селекторы по БЭМ выигрывают в скорости, потому что все являются простыми.

Кроме того, **различные типы селекторов** так же обрабатываются по-разному.

Есть несколько типов:
- по id
- по классу
- по имени тега
- универсальный (*)

Учитывая, что id должен быть единственным на странице — его поиск самый быстрый, а универсальный селектор самый медленный, потому что нужно пройтись по всему дереву и взять каждый элемент.

Другой пример, это **наследуемые свойства**. Сравним:

```
.list .item {
    list-style: none;
}
```

и

```
.list {
    list-style: none
}
```

В первом случае требуется найти каждый элемент списка и применить к нему правило, во втором случае — нужно найти всего один элемент, сам список.

Так же не стоит забывать про «мертвый код». Селекторы, которые есть в CSS, но в DOM таких элементов нет, очевидно, **будут обрабатываться зря**.

В свое время, программисты из Яндекс.Почты, проводили подробное исследование на эту тему. Наверняка, @pasaran и @doochik смогут дать ссылку или рассказать подробнее.

**Что почитать**
- [Про измерения с соответствующими выводами](https://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/)
- [Снука](https://smacss.com/book/selectors)
- [MDN по теме](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Writing_efficient_CSS)

**Comment by pasaran** [comment]
Все эти сведения про то, как там что матчится, идут аж из статьи примерно 2000-го года. С тех пор много воды утекло. Какие оптимизации появились в браузерах за последнее время — неизвестно.

Но вот, скажем, пятилетней давности статья: http://calendar.perfplanet.com/2011/css-selector-performance-has-changed-for-the-better/. Или вот еще свежее: https://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/.

Если кратко, то, скорее всего, скорость именно селекторов больше значения не имеет (в отличие от, скажем, самих css-свойств по этим селекторам).

А в BEM такие селекторы используются не потому, что они быстрые, а потому что их поддерживать легко.

**Comment by xenongattz** [comment]
@pasaran но ведь однозначно есть смысл не использовать например универсальный селектор, когда это не нужно? Или даже насчет него теперь можно не париться? Есть же, наверное какие-то основные критические моменты, которые каждому разработчику нужно знать?

**Comment by vitkarpov** [comment]
@xenongattz нашел любопытную статью на эту тему http://www.stevesouders.com/blog/2009/03/10/performance-impact-of-css-selectors/

Итог — современные браузеры уже все заоптимизировали как только можно, если и есть где-то бутылочное горлышко скорости работы приложения, то не в селекторах.
