### ISSUE TITLE
Как выбирать технологии и не обжигаться?

### ISSUE THREAD

**Issue by igoradamenko** [vitkarpov/ask-me#3]
Поскольку про JS ничего на ум не приходит, задам несколько философский вопрос. Как, в общем-то, жить?

С каждым днём вокруг всё больше и больше всего. Список интересных «штук» растёт не по дням, а по часам. Мой список «прочту попозже» уже давно перешёл за отметку в 1000 статей и никогда уже не вернётся обратно. Всё кажется крутым, увлекательным, интересным и прям воу-воу-воу, дайте две! Но когда всё доходит до дела, часто оказывается, что радугу тут в общем-то нарисовали и никакого золота под ней нет.

Как, будучи во фронтенде, выбирать правильные технологии, которые точно помогут, а не заставят костылять налево и направо? Как решить, что на Ангуляре пилить не будем, а вот Реакт можно и попробовать, и наоборот? Что учитывать при выборе: флексбоксы или по-старинке? Когда следует пойти на поводу «ой, это уже устарело, давайте перепишем!», а когда нет? 

И если совсем кратко, то вот так. Что нужно учитывать, при выборе технологий во фронтенде? Когда стоит рискнуть и попробовать что-то новое, а когда нет?

Вопрос размытый донельзя, но зато ответ может быть сколь угодно большим и максимально основанным на личном опыте.

**Comment by vitkarpov** [comment]
При выборе технологии важно помнить про [технологический хайп](http://www.gartner.com/technology/research/methodologies/hype-cycle.jsp) и оценить в какой точке кривой находится технология.

Интуитивно понятно, что если вокруг технологии много шума, она появилась недавно и «стремительно развивается» — не стоит завязывать на ней, скажем, ключевой проект или процессы компании. Имеет смысл попробовать на небольшом проекте, где цена ошибки невелика.

Если говорить о фронтенде, то зачастую речь идет о выборе MVC-фреймворка, NodeJS-фреймворка или классический холивар X или Y (например, Реакт или Ангуляр). Независимо от выбора, если писать что-то сложнее туду-листа, обязательно возникнут нетривиальные вопросы, ошибки в самих библиотеках.

**В решении этих вопросов помогает коммьюнити**.

Сперва стоит оценить:
- какая активность на гитхабе у проекта (не только количество звезд)
- сколько проектов в опенсорсе, с использованием данной библиотеки/фреймворка
- что говорит поиск по названию библиотеки/фреймворка на Стековерфлоу
- есть ли туториалы и скринкасты

Оценка вышеперечисленного помогает понять насколько активно коммьюнити и, соответственно, как быстро получится решать те или иные вопросы. Кроме того, коммьюнити обеспечивает появление соответствующих инструментов для разработки, например, чтобы удобнее писать тесты и дебажить.

В плане активности на гитхабе могу привести простой пример со [Стамбулом](https://github.com/gotwarlost/istanbul).

Страничка активности:
![2016-05-29_15-27-34](https://cloud.githubusercontent.com/assets/3001791/15633357/d28b46b8-25b3-11e6-9db5-fec627921780.png)

Соответственно, в issue никто не приходит (кроме ребят, которые пишут «столкнулся с тем же самым»). А вот и [мой issue](https://github.com/gotwarlost/istanbul/issues/635) — не трудно догадаться, что туда так же никто не пришел :)

Если говорить про «что лучше X или Y» — стоит посмотреть Квору и Стековерфлоу.

Например, вот популярный тредик «[Что лучше: flux+react или backbone+react](http://stackoverflow.com/questions/28815101/fluxreact-vs-backbonereact)»: хорошие ответы содержат ссылки, изучение которых, в итоге, помогает сложить некоторое собственное представление.

**Comment by vitkarpov** [comment]
Возможно, на эту тему сможет что-то рассказать @basvasilich, как руководитель большого числа хороших фронтенд-команд.

**Comment by igoradamenko** [comment]
@vitkarpov, спасибо, хорошие советы и ссылка на статью про хайп. Не видел её раньше :)

Да, было бы интересно послушать ещё и мнение Вадима на эту тему.

**Comment by vitkarpov** [comment]
Возможно, @oleggromov , руководитель группы фронтенд-разработки, сможет так же поделиться опытом.
