### ISSUE TITLE
Проектировать по БЭМ

### ISSUE THREAD

**Issue by proudwax** [vitkarpov/ask-me#5]
Задача: один modal и много button.
1. можно сделать один блок в самом верху страницы сразу после page, и в нём остальные блоки страницы, но так же будут присутствовать элементы button и modal.
2. на странице в нужных местах реализовывать блок с элементом button, а в конце страницы блок с элементом modal, (минус мне кажется в том, что после визуализации modal, в документе будет пустые 2 div`а)
3. вообще отдельные блоки и глобальный канал для вызова modal

**Comment by vitkarpov** [comment]
По смыслу, кажется, второй вариант наиболее приемлемым — это один блок, у него есть два элемента: логика по открытию попапа и т.д. будет сосредоточена в одном файле.

Пустые div'ы, по идее, не должны слишком мешать: браузеру все равно, а человеку важно, что в исходном коде, а не скомпилированном.

**Comment by vitkarpov** [comment]
На самом деле, подойдут все варианты.

Однако, первый мне кажется менее удобным, из-за того, что появляется некий «обрамляющий» блок, который нужен только, чтобы не появлялись пустые div'ы — кажется, не слишком логичным.

Последний вариант не очень удобен из-за того, что связь попапа и кнопок будет как раз через отдельный канал, разнесена по разным файлам (тех блоков, которые будут содержать кнопки и попап, в итоге) — кажется, не слишком удобным.
