### ISSUE TITLE
JS надежен?

### ISSUE THREAD

**Issue by xenongattz** [vitkarpov/ask-me#6]
Вопрос в топике немного странен, но я поясню.

Раньше, шанс того, что JS в браузере юзера отключен, был намного выше.
Поэтому предусматривались варианты, например, постинга формы обычным сабмитом, если JS отключен и аяксом её отправить нельзя. И так далее в этом духе.

Так вот, работаю над одним довольно большим проектом, я осознал, что JS всюду и без него как бы будет вообще не то и не так. Но, судя по всему, его поддержка столь повсеместна, что отключенность JS'а даже не стоит принимать в расчет. И больше думать в ключе совместимости кода?

Что думаешь по этому поводу?

**Comment by vitkarpov** [comment]
@xenongattz Действительно, сейчас в редком браузере не работает JS. Однако, здесь есть ловушка — на самом деле на каждом сайте «отключен» JS до тех пор пока он не загружен и не выполнен :)

Практически это имеет смысл на мобильных: там и сеть слабее, по которой нужно JS загружать, и сам компьютер, которому приходится этот JS выполнять.

Условно, я получил на телефон легкую страничку с кнопкой купить, но кнопку нажать не могу — либо JS еще не загрузился, либо тяжелое одностраничное приложение инициализируется и только греет руки телефоном.
