### ISSUE TITLE
Связать state to props

### ISSUE THREAD

**Issue by proudwax** [vitkarpov/ask-me#8]
Задача следующая, сделать модальное окно.

Подсмотрел у https://github.com/mui-org/material-ui/blob/303199d39b42a321d28347d8440d69166f872f27/packages/material-ui/src/Modal/Modal.js#L65

Получается, что в `<Modal>` передаётся `props: isVisible`, и уже внутри `Modal` идёт работа со `state`. 
`static getDerivedStateFromProps(nextProps) { ... ` жестко связывает `props -> state`. Но возникла проблема, что обратно не изменить `state -> props`

Возможно ли такое сделать, и правильный ли это подход? Ведь React строится сверху вниз.

**Comment by vitkarpov** [comment]
Это решается прокидыванием в дочерние пропсы функции, которая будет менять стейт родительского компонента при изменениях в дочернем.

Например,

```js
<Modal
  onVisibilityChange={(visible) => {
    // do something, you know visibility state from arguments
  }}
/>
```

В самом компоненте соответственно нужно вызывать `this.props.onVisibilityChanged` каждый раз когда меняется стейт и прокидывать туда нужное состояние.

**Comment by vitkarpov** [comment]
Ты правильно говоришь, что React «только сверху вниз».

**Comment by proudwax** [comment]
В этом и проблема, что мы должны прокидывать функцию, для того, чтоб изменить состояние родителя. А хотелось сделать проще `<Modal isVisible={true/false}>...</Modal>`. Не уже ли нельзя такого смастерить?

**Comment by vitkarpov** [comment]
В тот момент когда люди устали прокидывать колбеки — появился flux, а за ним redux. Советую посмотреть в эту сторону.
